import { BASE_CONSTANT_ARRIVAL_RATE } from "../base_scenario.js";

var CONSTANT_ARRIVAL_RATE = BASE_CONSTANT_ARRIVAL_RATE;
CONSTANT_ARRIVAL_RATE["rate"] = 1;
CONSTANT_ARRIVAL_RATE["timeUnit"] = "10s";
CONSTANT_ARRIVAL_RATE["maxVUs"] = 100;
CONSTANT_ARRIVAL_RATE["exec"] = "search";

export { CONSTANT_ARRIVAL_RATE };
